// properties-data.js - Complete Belgaum Property Listings

const properties = [
  // ========== SHAHAPUR AREA (Premium Location) ==========
  {
    title: "Luxury 3BHK in Shahapur",
    price: "₹85,00,000",
    priceValue: 8500000,
    size: "1500 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    area: "Shahapur",
    location: "Near City Center Mall",
    description: "Premium apartment with modern amenities in the heart of Belgaum. This spacious 3BHK offers luxury living with all modern conveniences including a gym, swimming pool, and 24/7 security.",
    advantages: ["Close to schools", "Market nearby", "Parking available", "24/7 Security", "Power Backup"],
    amenities: ["Gym", "Swimming Pool", "24/7 Security", "Power Backup", "Children's Play Area", "Club House"],
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: false,
    isExclusive: true
  },
  {
    title: "2BHK Premium Apartment - Shahapur",
    price: "₹65,00,000",
    priceValue: 6500000,
    size: "1200 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Shahapur",
    location: "Near Maruti Galli",
    description: "Well-designed 2BHK with modern interiors and excellent ventilation. Located in a peaceful residential area with easy access to all amenities.",
    advantages: ["Walking distance to market", "Near temple", "Gated community", "Children's play area"],
    amenities: ["Gym", "Parking", "Security", "Lift", "Children's Play Area"],
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },
  {
    title: "Shahapur Luxury Villa",
    price: "₹1,50,00,000",
    priceValue: 15000000,
    size: "2500 sq ft",
    bedrooms: 4,
    bathrooms: 4,
    area: "Shahapur",
    location: "Near Club Road",
    description: "Stunning luxury villa with private garden and swimming pool. Perfect for large families seeking premium living in Belgaum's most sought-after locality.",
    advantages: ["Private garden", "Swimming pool", "4 car parking", "Premium finishes", "Gated community"],
    amenities: ["Private Pool", "Gym", "Garden", "Security", "Club House", "24/7 Power Backup"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: true,
    isExclusive: true
  },

  // ========== TILAKWADI AREA ==========
  {
    title: "Spacious 2BHK in Tilakwadi",
    price: "₹55,00,000",
    priceValue: 5500000,
    size: "1100 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Tilakwadi",
    location: "Near Tilakwadi Market",
    description: "Well-maintained apartment with excellent connectivity. Peaceful neighborhood with all amenities nearby including schools, hospitals, and shopping.",
    advantages: ["Walking distance to market", "Public transport nearby", "Quiet neighborhood", "Well-lit roads"],
    amenities: ["Parking", "Security", "Lift", "24x7 Water Supply", "Intercom"],
    images: ["https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },
  {
    title: "3BHK Luxury Villa - Tilakwadi",
    price: "₹1,20,00,000",
    priceValue: 12000000,
    size: "2000 sq ft",
    bedrooms: 3,
    bathrooms: 3,
    area: "Tilakwadi",
    location: "Near Ramdev Galli",
    description: "Independent villa with garden and parking. Features modern architecture with high-quality finishes and spacious living areas.",
    advantages: ["Private garden", "Independent house", "Great locality", "2 car parking"],
    amenities: ["Private Garden", "2 Car Parking", "Security", "Solar Panels", "Water Softener"],
    images: ["https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: false,
    isExclusive: true
  },

  // ========== CAMP AREA ==========
  {
    title: "Modern 2BHK in Camp Area",
    price: "₹65,00,000",
    priceValue: 6500000,
    size: "1250 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Camp",
    location: "Near Military Hospital",
    description: "Newly constructed apartment in prime Camp area. Ideal for families and working professionals with excellent connectivity to all parts of the city.",
    advantages: ["Close to railway station", "Commercial area nearby", "Good road connectivity", "Banks nearby"],
    amenities: ["Gym", "Parking", "Security", "Intercom", "Lift", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800"],
    premium: true,
    featured: false,
    isNewLaunch: true,
    isExclusive: false
  },
  {
    title: "3BHK Army Quarters Style - Camp",
    price: "₹75,00,000",
    priceValue: 7500000,
    size: "1400 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    area: "Camp",
    location: "Near Clock Tower",
    description: "Spacious apartment with vintage charm and modern amenities. Located in the historic Camp area with excellent access to commercial establishments.",
    advantages: ["Heritage area", "Close to cantonment", "Well-connected", "Green surroundings"],
    amenities: ["Parking", "Security", "Power Backup", "Water Softener", "Community Hall"],
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== RPD CROSS AREA ==========
  {
    title: "Premium 4BHK at RPD Cross",
    price: "₹1,25,00,000",
    priceValue: 12500000,
    size: "2200 sq ft",
    bedrooms: 4,
    bathrooms: 3,
    area: "RPD Cross",
    location: "Near RPD College",
    description: "Spacious luxury apartment with stunning city views. Perfect for large families seeking premium living with all modern amenities.",
    advantages: ["Panoramic views", "Large balconies", "Premium finishes", "Wide roads", "Near educational institutions"],
    amenities: ["Swimming Pool", "Club House", "Gym", "Jogging Track", "Landscaped Gardens", "Children's Play Area"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: true,
    isExclusive: true
  },
  {
    title: "2BHK Budget Friendly - RPD Cross",
    price: "₹48,00,000",
    priceValue: 4800000,
    size: "950 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "RPD Cross",
    location: "Near Hanuman Nagar",
    description: "Affordable apartment with all basic amenities. Perfect for small families and first-time home buyers looking for value for money.",
    advantages: ["Good connectivity", "Schools nearby", "Hospital nearby", "Affordable maintenance"],
    amenities: ["Parking", "Security", "Water Supply", "Community Hall"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== GOGTE CHOWK AREA ==========
  {
    title: "Affordable 1BHK in Gogte Chowk",
    price: "₹35,00,000",
    priceValue: 3500000,
    size: "750 sq ft",
    bedrooms: 1,
    bathrooms: 1,
    area: "Gogte Chowk",
    location: "Near Gogte College",
    description: "Perfect for bachelors, students, and small families looking for an affordable home in a prime location. Close to educational institutions and commercial areas.",
    advantages: ["Budget-friendly", "Near college", "Good connectivity", "Affordable maintenance", "Close to bus stop"],
    amenities: ["Parking", "Security", "24x7 Water Supply", "Maintained common areas"],
    images: ["https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },
  {
    title: "2BHK Near KLE University",
    price: "₹52,00,000",
    priceValue: 5200000,
    size: "1050 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Gogte Chowk",
    location: "Near KLE University",
    description: "Perfect for students and faculty members. Well-maintained apartment with easy access to the university and other educational institutions.",
    advantages: ["Walking distance to university", "Student-friendly", "Good rental income", "24/7 security"],
    amenities: ["Parking", "Security", "Study Room", "WiFi Ready", "Water Supply"],
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf215d?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: true,
    isExclusive: false
  },

  // ========== VADAGAON AREA ==========
  {
    title: "3BHK New Launch - Vadagaon",
    price: "₹78,00,000",
    priceValue: 7800000,
    size: "1450 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    area: "Vadagaon",
    location: "Near Vishwanath Nagar",
    description: "Newly launched residential project with modern amenities. Features spacious rooms, high-quality finishes, and excellent ventilation.",
    advantages: ["New construction", "Modern design", "Vastu compliant", "Good ventilation"],
    amenities: ["Gym", "Swimming Pool", "Club House", "Parking", "Security", "Children's Play Area"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: true,
    isExclusive: false
  },
  {
    title: "2BHK Vadagaon - Near Bus Stand",
    price: "₹48,00,000",
    priceValue: 4800000,
    size: "980 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Vadagaon",
    location: "Near Vadagaon Bus Stand",
    description: "Conveniently located near public transport. Well-maintained apartment with all basic amenities and excellent connectivity.",
    advantages: ["Excellent connectivity", "Close to market", "Affordable", "Good rental income"],
    amenities: ["Parking", "Security", "Lift", "Water Supply"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== MACHHE AREA ==========
  {
    title: "Luxury 3BHK - Machhe",
    price: "₹92,00,000",
    priceValue: 9200000,
    size: "1600 sq ft",
    bedrooms: 3,
    bathrooms: 3,
    area: "Machhe",
    location: "Near Machhe Industrial Area",
    description: "Premium apartment for working professionals. Features modern amenities, spacious rooms, and excellent connectivity to industrial areas.",
    advantages: ["Close to industrial area", "Good for professionals", "Modern amenities", "Excellent connectivity"],
    amenities: ["Gym", "Swimming Pool", "Club House", "Party Hall", "Garden", "24/7 Security"],
    images: ["https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800"],
    premium: true,
    featured: false,
    isNewLaunch: true,
    isExclusive: false
  },
  {
    title: "1BHK for Bachelors - Machhe",
    price: "₹32,00,000",
    priceValue: 3200000,
    size: "680 sq ft",
    bedrooms: 1,
    bathrooms: 1,
    area: "Machhe",
    location: "Near Machhe Circle",
    description: "Budget-friendly option for bachelors and students. Well-maintained apartment with basic amenities and good security.",
    advantages: ["Affordable rent", "Near bus stop", "Safe locality", "Good for bachelors"],
    amenities: ["Parking", "Security", "Water Supply", "Maintained common areas"],
    images: ["https://images.unsplash.com/photo-1560185008-5b0f6d0f1bf9?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== SAMBHAJI NAGAR AREA ==========
  {
    title: "3BHK Premium - Sambhaji Nagar",
    price: "₹88,00,000",
    priceValue: 8800000,
    size: "1550 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    area: "Sambhaji Nagar",
    location: "Near Sambhaji Garden",
    description: "Beautiful apartment with garden view. Features spacious rooms, modern amenities, and a peaceful environment.",
    advantages: ["Garden facing", "Peaceful area", "Well-maintained", "Good ventilation"],
    amenities: ["Gym", "Parking", "Security", "Power Backup", "Garden", "Children's Play Area"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    premium: true,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },
  {
    title: "2BHK Family Home - Sambhaji Nagar",
    price: "₹58,00,000",
    priceValue: 5800000,
    size: "1080 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Sambhaji Nagar",
    location: "Near Market Yard",
    description: "Perfect for families with children. Well-maintained apartment with good security and all basic amenities.",
    advantages: ["Schools nearby", "Hospital nearby", "Safe locality", "Good community"],
    amenities: ["Parking", "Security", "Children's Play Area", "Water Supply"],
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== HINDUSTAN PETROLEUM AREA ==========
  {
    title: "2BHK Near HP Petrol Pump",
    price: "₹52,00,000",
    priceValue: 5200000,
    size: "1000 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Hindustan Petroleum",
    location: "Near HP Petrol Bunk",
    description: "Conveniently located near main highway. Perfect for commuters and professionals with excellent connectivity.",
    advantages: ["Excellent connectivity", "Close to highway", "Good for commuters", "Easy access to city"],
    amenities: ["Parking", "Security", "Water Supply", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf215d?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== UDYAMBAG AREA ==========
  {
    title: "3BHK Row House - Udyambag",
    price: "₹95,00,000",
    priceValue: 9500000,
    size: "1700 sq ft",
    bedrooms: 3,
    bathrooms: 3,
    area: "Udyambag",
    location: "Near Udyambag Police Station",
    description: "Spacious row house with private terrace. Features modern architecture, good ventilation, and a secure neighborhood.",
    advantages: ["Private terrace", "Independent house", "Good locality", "Safe neighborhood"],
    amenities: ["Private Terrace", "Car Parking", "Security", "Garden Area", "Water Softener"],
    images: ["https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800"],
    premium: true,
    featured: true,
    isNewLaunch: true,
    isExclusive: true
  },
  {
    title: "1BHK Affordable - Udyambag",
    price: "₹30,00,000",
    priceValue: 3000000,
    size: "650 sq ft",
    bedrooms: 1,
    bathrooms: 1,
    area: "Udyambag",
    location: "Near Udyambag Temple",
    description: "Most affordable option in prime location. Perfect for small families, bachelors, and senior citizens.",
    advantages: ["Very affordable", "Close to temple", "Good for seniors", "Safe locality"],
    amenities: ["Parking", "Water Supply", "Security", "Maintained common areas"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  },

  // ========== HANUMAN NAGAR AREA ==========
  {
    title: "2BHK Near Hanuman Temple",
    price: "₹45,00,000",
    priceValue: 4500000,
    size: "920 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    area: "Hanuman Nagar",
    location: "Near Hanuman Temple",
    description: "Well-connected residential area with good community living. Perfect for families looking for a peaceful neighborhood.",
    advantages: ["Temple nearby", "Good community", "Affordable", "Peaceful area"],
    amenities: ["Parking", "Security", "Water Supply", "Children's Play Area"],
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"],
    premium: false,
    featured: false,
    isNewLaunch: false,
    isExclusive: false
  }
];

module.exports = properties;